name: 19 - 1 - Managin Concurrency

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    ping:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Ping URL
              id: ping-url
              uses: ./.github/actions/docker-ping-url
              with:
                url: http://www.asdfghjkl.com/
                max_trials: 20
                delay: 5
              
              